export const CATALOG: readonly string[] = [
  "😀", "😂", "😍", "😎", "🤓", "🥳", "😭", "😡", "🥶", "🤠",
  "💀", "👻", "👽", "🤖", "🎃", "🤡", "💩", "👾", "🦄", "🐲",
  "🐱", "🐶", "🦊", "🐻", "🐼", "🐨", "🐯", "🦁", "🐮", "🐷",
  "🐸", "🐵", "🐧", "🦉", "🐺", "🐴", "🐝", "🦋", "🐙", "🦑",
  "🦀", "🐡", "🐠", "🐬", "🐳", "🦈", "🐢", "🐍", "🦎", "🐘",
  "☕", "🍵", "🍕", "🍔", "🌮", "🍣", "🍩", "🍪", "🍺", "🍷",
  "🌈", "⭐", "🌙", "⚡", "🔥", "💧", "❄️", "🌊", "🌸", "🌹",
  "🍀", "🍁", "🍄", "🌵", "🌍", "🪐", "🚀", "⚙️", "💎", "🔮",
];

export const CATALOG_NAMES: Record<string, string> = {
  "😀": "grin",
  "😂": "tears",
  "😍": "hearts",
  "😎": "shades",
  "🤓": "nerd",
  "🥳": "party",
  "😭": "sob",
  "😡": "rage",
  "🥶": "freeze",
  "🤠": "cowboy",
  "💀": "skull",
  "👻": "ghost",
  "👽": "alien",
  "🤖": "robot",
  "🎃": "pumpkin",
  "🤡": "clown",
  "💩": "poop",
  "👾": "invader",
  "🦄": "unicorn",
  "🐲": "dragon",
  "🐱": "cat",
  "🐶": "dog",
  "🦊": "fox",
  "🐻": "bear",
  "🐼": "panda",
  "🐨": "koala",
  "🐯": "tiger",
  "🦁": "lion",
  "🐮": "cow",
  "🐷": "pig",
  "🐸": "frog",
  "🐵": "monkey",
  "🐧": "penguin",
  "🦉": "owl",
  "🐺": "wolf",
  "🐴": "horse",
  "🐝": "bee",
  "🦋": "moth",
  "🐙": "octopus",
  "🦑": "squid",
  "🦀": "crab",
  "🐡": "puffer",
  "🐠": "fish",
  "🐬": "dolphin",
  "🐳": "whale",
  "🦈": "shark",
  "🐢": "turtle",
  "🐍": "snake",
  "🦎": "lizard",
  "🐘": "elephant",
  "☕": "coffee",
  "🍵": "tea",
  "🍕": "pizza",
  "🍔": "burger",
  "🌮": "taco",
  "🍣": "sushi",
  "🍩": "donut",
  "🍪": "cookie",
  "🍺": "beer",
  "🍷": "wine",
  "🌈": "prism",
  "⭐": "star",
  "🌙": "moon",
  "⚡": "volt",
  "🔥": "flame",
  "💧": "drop",
  "❄️": "frost",
  "🌊": "tide",
  "🌸": "bloom",
  "🌹": "rose",
  "🍀": "clover",
  "🍁": "maple",
  "🍄": "toadstool",
  "🌵": "cactus",
  "🌍": "earth",
  "🪐": "saturn",
  "🚀": "rocket",
  "⚙️": "gear",
  "💎": "gem",
  "🔮": "orb",
};

const PICTO =
  /\p{Extended_Pictographic}(?:\uFE0F|\u200D\p{Extended_Pictographic}\uFE0F?)*/u;

export function firstEmoji(raw: string): string {
  const trimmed = raw.trim();
  if (!trimmed) return "";
  const hit = trimmed.match(PICTO);
  return hit?.[0] ?? "";
}

export function labelOf(glyph: string): string {
  return CATALOG_NAMES[glyph] ?? "glyph";
}
